name: GNnRank
channels:
  - stellargraph
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.12.0=py36h06a4308_0
  - alabaster=0.7.12=py36_0
  - argh=0.26.2=py36_0
  - argon2-cffi=20.1.0=py36h27cfd23_1
  - astroid=2.5=py36h06a4308_1
  - astunparse=1.6.3=py_0
  - async_generator=1.10=py36h28b3542_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.5=pyhd3eb1b0_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blinker=1.4=py36h06a4308_0
  - boto3=1.17.46=pyhd3eb1b0_0
  - botocore=1.20.73=pyhd3eb1b0_1
  - brotlipy=0.7.0=py36h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.5=py36h261ae71_0
  - chardet=4.0.0=py36h06a4308_1003
  - click=8.0.0=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py36h27cfd23_2
  - cpuonly=1.0=0
  - cryptography=3.4.6=py36hd23ed53_0
  - cycler=0.10.0=py36_0
  - cython=0.29.23=py36h2531618_0
  - dataclasses=0.8=pyh4f3eec9_6
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=py_0
  - docutils=0.16=py36_1
  - entrypoints=0.3=py36_0
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.2.2=h20bf706_0
  - flake8=3.9.0=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - future=0.18.2=py36_1
  - gast=0.3.3=py_0
  - gensim=3.8.3=py36h2531618_2
  - glib=2.67.4=h36276a3_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.5=h71b1129_1002
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-cloud-core=1.6.0=pyhd3eb1b0_0
  - google-cloud-storage=1.38.0=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py36h27cfd23_0
  - google-pasta=0.2.0=py_0
  - google-resumable-media=1.2.0=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py36h06a4308_0
  - grpcio=1.36.1=py36h2157cd5_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=3.7.3=py36h06a4308_1
  - importlib_metadata=3.7.3=hd3eb1b0_1
  - intel-openmp=2020.2=254
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - isort=5.7.0=pyhd3eb1b0_0
  - jedi=0.14.1=py36_0
  - jeepney=0.6.0=pyhd3eb1b0_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jmespath=0.10.0=py_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py36h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyring=22.3.0=py36h06a4308_0
  - kiwisolver=1.3.1=py36h2531618_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.5.2=py36h27cfd23_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcrc32c=1.1.1=he6710b0_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libllvm10=10.0.1=he513fc3_3
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=he6710b0_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h3942068_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.4=py36h06a4308_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.3.4=py36h06a4308_0
  - matplotlib-base=3.3.4=py36h62a2d02_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - multidict=5.1.0=py36h27cfd23_2
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.4.1=hbb512f6_0
  - networkx=2.5=py_0
  - ninja=1.10.2=py36hff7bd54_0
  - notebook=6.2.0=py36h06a4308_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py36_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.1.3=py36he6710b0_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py36h06a4308_1
  - parso=0.5.2=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py36he98fc37_0
  - pip=21.0.1=py36h06a4308_0
  - pluggy=0.13.1=py36_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - psutil=5.8.0=py36h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pydocstyle=5.1.1=py_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyjwt=1.7.1=py36_0
  - pylint=2.7.2=py36h06a4308_1
  - pympler=0.9=py_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.17.3=py36h7b6447c_0
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.13=hdb3f193_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-jsonrpc-server=0.3.4=py_1
  - python-language-server=0.31.9=py36_0
  - python_abi=3.6=2_cp36m
  - pytorch=1.8.0=py3.6_cpu_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=5.4.1=py36h27cfd23_1
  - pyzmq=20.0.0=py36h2531618_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=1.0.1=py_0
  - qtconsole=5.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rope=0.18.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=0.9.4=py36_1
  - s3transfer=0.3.6=pyhd3eb1b0_0
  - secretstorage=3.3.1=py36h06a4308_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py36h06a4308_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py36h06a4308_0
  - smart_open=5.0.0=pyhd3eb1b0_0
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.3.0=pyhd3eb1b0_0
  - sparse=0.12.0=pyhd8ed1ab_0
  - sphinx=3.5.2=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
  - spyder=4.0.0=py36_0
  - spyder-kernels=1.8.1=py36_0
  - sqlite=3.35.1=hdfb4753_0
  - stellargraph=1.2.1=py_0
  - tbb=2020.2=hc9558a2_0
  - tensorflow=2.2.0=mkl_py36h5a57954_0
  - tensorflow-base=2.2.0=mkl_py36hd506778_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - termcolor=1.1.0=py36h06a4308_1
  - terminado=0.9.3=py36h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchaudio=0.8.0=py36
  - torchvision=0.9.0=py36_cpu
  - tornado=6.1=py36h27cfd23_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.2=py36h27cfd23_1
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - ujson=1.35=py36h14c3975_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - watchdog=1.0.2=py36h06a4308_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.12.1=py36h7b6447c_1
  - wurlitzer=2.0.1=py36_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.5.1=py36h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - ase==3.21.1
    - cached-property==1.5.2
    - cachetools==4.2.1
    - cvxpy==1.1.11
    - dgl==0.6.0.post1
    - ecos==2.0.7.post1
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - googledrivedownloader==0.4
    - h5py==3.1.0
    - isodate==0.6.0
    - latextable==0.1.1
    - llvmlite==0.36.0
    - madgrad==1.0
    - numba==0.53.0
    - osqp==0.6.2.post0
    - protobuf==3.15.6
    - pyasn1-modules==0.2.8
    - python-louvain==0.15
    - pytorch-model-summary==0.1.2
    - qdldl==0.1.5.post0
    - rdflib==5.0.0
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - scs==2.1.2
    - signet==0.1.0
    - sklearn==0.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - texttable==1.6.3
    - torch-cluster==1.5.9
    - torch-geometric==1.6.3
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9
    - torch-spline-conv==1.2.1
    - torch-tb-profiler==0.1.0
    - torchtext==0.9.0
    - tqdm==4.59.0
prefix: /data/localhost/yhe/miniconda3/envs/GNNRank
