name: GNNRank
channels:
  - stellargraph
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py37h7f8727e_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=py37_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - arrow=0.13.1=py37_0
  - astor=0.8.1=py37h06a4308_0
  - astroid=2.6.6=py37h06a4308_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - async_generator=1.10=py37h28b3542_0
  - asynctest=0.13.0=py_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blinker=1.4=py37h06a4308_0
  - boto3=1.18.21=pyhd3eb1b0_0
  - botocore=1.21.41=pyhd3eb1b0_1
  - bottleneck=1.3.2=py37heb32a55_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cached-property=1.5.2=py_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - chardet=4.0.0=py37h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cookiecutter=1.7.2=pyhd3eb1b0_0
  - cryptography=3.4.8=py37hd23ed53_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - daal4py=2021.4.0=py37h78b71dc_0
  - dal=2021.4.0=h06a4308_729
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - docutils=0.18.1=py37h06a4308_2
  - entrypoints=0.3=py37_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py37h7f8727e_0
  - gast=0.2.2=py37_0
  - gensim=3.8.3=py37h2531618_2
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-cloud-core=1.7.1=pyhd3eb1b0_0
  - google-cloud-storage=1.41.0=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py37h27cfd23_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py37h06a4308_0
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - grpcio=1.42.0=py37hce63b2e_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.6.0=py37ha0f2276_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py37h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - inflection=0.5.1=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.4.1=py37h06a4308_1
  - ipython=7.29.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.0=py37h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - keyring=23.4.0=py37h06a4308_0
  - kiwisolver=1.3.1=py37h2531618_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.6.0=py37h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcrc32c=1.1.1=he6710b0_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py37h06a4308_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.5.0=py37h06a4308_0
  - matplotlib-base=3.5.0=py37h3ed280b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - multidict=5.2.0=py37h7f8727e_2
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py37h06a4308_1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd3eb1b0_0
  - notebook=6.4.6=py37h06a4308_0
  - numexpr=2.8.1=py37h6abb31d_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=py37_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1l=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.4=py37h8c16a72_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pathspec=0.7.0=py_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.2.2=py37h06a4308_0
  - pluggy=1.0.0=py37h06a4308_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.17.2=py37h295c915_0
  - psutil=5.8.0=py37h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pyg=2.0.3=py37_torch_1.10.0_cu102
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyjwt=2.1.0=py37h06a4308_0
  - pylint=2.9.6=py37h06a4308_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-louvain=0.15=pyhd3deb0d_0
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.1=py3.7_cuda10.2_cudnn7.6.5_0
  - pytorch-cluster=1.5.9=py37_torch_1.10.0_cu102
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py37_torch_1.10.0_cu102
  - pytorch-sparse=0.6.12=py37_torch_1.10.0_cu102
  - pytorch-spline-conv=1.2.1=py37_torch_1.10.0_cu102
  - pytz=2021.3=pyhd3eb1b0_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h5e8e339_0
  - pyzmq=22.3.0=py37h295c915_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - regex=2021.8.3=py37h7f8727e_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rope=0.21.1=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=0.9.7=py37h06a4308_1
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - scikit-learn=1.0.1=py37h51133e4_0
  - scikit-learn-intelex=2021.4.0=py37h06a4308_0
  - scipy=1.7.1=py37h292c36d_2
  - secretstorage=3.3.1=py37h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - smart_open=5.1.0=pyhd3eb1b0_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=1.8.5=py37_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=5.1.5=py37h06a4308_1
  - spyder-kernels=2.1.3=py37h06a4308_0
  - sqlite=3.37.0=hc218d9a_0
  - stellargraph=1.2.1=py_0
  - tbb=2021.4.0=hd09550d_0
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=mkl_py37h80a91df_0
  - tensorflow-base=2.1.0=mkl_py37h6d63fb7_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=1.1.0=py37h06a4308_1
  - terminado=0.9.4=py37h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.10.1=py37_cu102
  - torchvision=0.11.2=py37_cu102
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py37h7f8727e_1
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - ujson=4.2.0=py37h295c915_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - watchdog=2.1.6=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - wurlitzer=3.0.2=py37h06a4308_0
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h516909a_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.5.1=py37h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - latextable==0.2.1
    - llvmlite==0.37.0
    - numba==0.54.1
    - numpy==1.20.3
    - sparse==0.13.0
    - texttable==1.6.4
prefix: /data/anaconda3/envs/GNNRank
