name: ranking
channels:
  - stellargraph
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.3.0=mkl
  - absl-py=0.12.0=py36h06a4308_0
  - aiohttp=3.7.4=py36h27cfd23_1
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py36h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py36h06a4308_0
  - boto3=1.17.46=pyhd3eb1b0_0
  - botocore=1.20.73=pyhd3eb1b0_1
  - brotlipy=0.7.0=py36h27cfd23_1003
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.4.13=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2020.12.5=py36h06a4308_0
  - cffi=1.14.5=py36h261ae71_0
  - click=8.0.0=pyhd3eb1b0_0
  - coverage=5.5=py36h27cfd23_2
  - cryptography=3.4.7=py36hd23ed53_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py36_0
  - cython=0.29.23=py36h2531618_0
  - dataclasses=0.7=py36_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - gast=0.3.3=py_0
  - gensim=3.8.3=py36h2531618_2
  - glib=2.66.1=h92f7085_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.30.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-cloud-core=1.6.0=pyhd3eb1b0_0
  - google-cloud-storage=1.38.0=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py36h27cfd23_0
  - google-pasta=0.2.0=py_0
  - google-resumable-media=1.2.0=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py36h06a4308_0
  - grpcio=1.36.1=py36h2157cd5_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - idna_ssl=1.1.0=py36h06a4308_0
  - importlib-metadata=3.10.0=py36h06a4308_0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py36_0
  - jmespath=0.10.0=py_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py36h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.0=py36h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcrc32c=1.1.1=he6710b0_2
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.4=py36h06a4308_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py36h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - multidict=5.1.0=py36h27cfd23_2
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.1=py36hfd86e86_0
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py36_0
  - openssl=1.1.1k=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.1.3=py36he6710b0_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.0.1=py36he98fc37_0
  - pip=20.2.4=py36h06a4308_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - protobuf=3.14.0=py36h2531618_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyjwt=1.7.1=py36_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.7.1=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.7.1=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.1=py_0
  - pyzmq=20.0.0=py36h2531618_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.3.6=pyhd3eb1b0_0
  - scipy=1.5.2=py36h0b6359f_0
  - setuptools=50.3.1=py36h06a4308_1
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py36h06a4308_0
  - smart_open=5.0.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - stellargraph=1.2.1=py_0
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=mkl_py36h5a57954_0
  - tensorflow-base=2.2.0=mkl_py36hd506778_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - termcolor=1.1.0=py36h06a4308_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.2=py36
  - torchvision=0.8.2=py36_cu102
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.55.1=pyhd3eb1b0_0
  - traitlets=4.3.3=py36_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.2.5=py_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.12.1=py36h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yarl=1.5.1=py36h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - ase==3.20.1
    - cached-property==1.5.2
    - chardet==4.0.0
    - cvxpy==1.1.7
    - ecos==2.0.7.post1
    - future==0.18.2
    - googledrivedownloader==0.4
    - h5py==3.1.0
    - isodate==0.6.0
    - jinja2==2.11.2
    - joblib==0.17.0
    - latextable==0.1.1
    - llvmlite==0.35.0
    - markupsafe==1.1.1
    - numba==0.52.0
    - osqp==0.6.1
    - python-louvain==0.15
    - rdflib==5.0.0
    - scikit-learn==0.23.2
    - scs==2.1.2
    - signet==0.1.0
    - sklearn==0.0
    - sparse==0.12.0
    - texttable==1.6.3
    - torch-cluster==1.5.8
    - torch-geometric==1.6.3
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - urllib3==1.26.2
prefix: /homes/yhe/miniconda3/envs/pytorch
